version: '3'

services:
  asterisk:
    image: izdock/izpbx-asterisk:16
    restart: always
    depends_on:
      - db
    ports:
    - ${APP_PORT_HTTP}:80
    - ${APP_PORT_HTTPS}:443
    - ${APP_PORT_FOP}:4445
    - ${APP_PORT_IAX}:4569
    - ${APP_PORT_PJSIP}:5060
    - ${APP_PORT_SIP}:5160
    - ${APP_PORT_IAX}:4569/udp
    - ${APP_PORT_PJSIP}:5060/udp
    - ${APP_PORT_SIP}:5160/udp
    - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
    volumes:
    - ./data/asterisk:/data
    env_file:
    - .env
    networks:
    - izpbx
    ### fail2ban need privileged mode
    cap_add:
    - NET_ADMIN
    privileged: true

  db:
    image: mariadb:10.4
    restart: always
    ports:
    - ${APP_PORT_MYSQL}:3306
    volumes:
    - ./data/db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    networks:
    - izpbx

networks:
  izpbx:
