version: '3'

# if 'network_mode: host' is disabled, comment out the following lines
networks:
  izpbx:

services:
  izpbx:
    container_name: izpbx
    hostname: ${APP_FQDN}
    image: izdock/izpbx-asterisk:0.9.2
    restart: always
    depends_on:
    - db
    ports:
    - ${APP_PORT_HTTP}:${APP_PORT_HTTP}
    - ${APP_PORT_HTTPS}:${APP_PORT_HTTPS}
    - ${APP_PORT_FOP2}:${APP_PORT_FOP2}
    - ${APP_PORT_IAX}:${APP_PORT_IAX}
    - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}
    - ${APP_PORT_SIP}:${APP_PORT_SIP}
    - ${APP_PORT_IAX}:${APP_PORT_IAX}/udp
    - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}/udp
    - ${APP_PORT_SIP}:${APP_PORT_SIP}/udp
    - ${APP_PORT_ZABBIX}:${APP_PORT_ZABBIX}
    - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/izpbx:/data
    env_file:
    - .env
    ### fail2ban need privileged mode to manage iptables
    cap_add:
    - NET_ADMIN
    privileged: true
    # for simpler sip nat management use: 'network_mode: host'
    network_mode: host
    # if 'network_mode: host' is disabled, comment out the following lines
    #links: 
    #- db
    #networks:
    #- izpbx
    
  db:
    container_name: izpbx-db
    image: mariadb:10.4
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    restart: always
    # database configurations (WARNING: if commented out, the database will be exposed outside the container)
    ports:
    - ${APP_PORT_MYSQL}:3306
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/db:/var/lib/mysql
    env_file:
    - .env
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    #network_mode: host
    # if 'network_mode: host' is disabled, comment out the following lines
    networks:
    - izpbx
