version: '3'

#networks:
#  izpbx:

services:
  izpbx:
    container_name: izpbx
    hostname: ${APP_FQDN}
    image: izdock/izpbx-asterisk:16
    restart: always
    depends_on:
    - db
    ports:
    - ${APP_PORT_HTTP}:${APP_PORT_HTTP}
    - ${APP_PORT_HTTPS}:${APP_PORT_HTTPS}
    - ${APP_PORT_FOP}:${APP_PORT_FOP}
    - ${APP_PORT_IAX}:${APP_PORT_IAX}
    - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}
    - ${APP_PORT_SIP}:${APP_PORT_SIP}
    - ${APP_PORT_IAX}:${APP_PORT_IAX}/udp
    - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}/udp
    - ${APP_PORT_SIP}:${APP_PORT_SIP}/udp
    - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
    volumes:
    - ./data/asterisk:/data
    env_file:
    - .env
    ### fail2ban need privileged mode
    cap_add:
    - NET_ADMIN
    privileged: true
    network_mode: host
    #links: 
    #- db
    #networks:
    #- izpbx
    
  db:
    container_name: izpbx-db
    image: mariadb:10.4
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    restart: always
    #ports:
    #- ${APP_PORT_MYSQL}:3306
    volumes:
    - ./data/db:/var/lib/mysql
    env_file:
    - .env
    environment:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_PASSWORD
    network_mode: host
    #network_mode: bridge
    #networks:
    #- izpbx
